service: poc-lambda-puppeteer

provider:
  name: aws
  runtime: nodejs16.x
  stage: poc
  region: sa-east-1
  memorySize: 2048
  timeout: 90
  logRetentionInDays: 1

  environment:
    NODE_ENV: "production"

functions:
  handler:
    handler: index.runner
    layers:
      - !Sub 'arn:aws:lambda:sa-east-1:764866452798:layer:chrome-aws-lambda:31'
    events:
      - schedule: rate(1 minute)